### ISSUE TITLE
How to solve this error ？

### ISSUE THREAD

**Issue by bingoku** [victorcampos/harbor#11]
`[root@aliyun Deploy]# docker-compose kill
Killing deploy_ui_1 ...

ERROR: for deploy_ui_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 9, in <module>
    load_entry_point('docker-compose==1.8.0', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python2.7/site-packages/compose/cli/main.py", line 61, in main
    command()
  File "/usr/lib/python2.7/site-packages/compose/cli/main.py", line 113, in perform_command
    handler(command, command_options)
  File "/usr/lib64/python2.7/contextlib.py", line 35, in **exit**
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.7/site-packages/compose/cli/errors.py", line 56, in handle_connection_errors
    log_timeout_error()
TypeError: log_timeout_error() takes exactly 1 argument (0 given)`

**Comment by Binternet** [comment]
+1
